language: node_js
node_js:
- stable
services:
- postgresql
before_script:
- psql -c 'create database monday;' -U postgres
- psql -c "CREATE USER admin WITH PASSWORD '12345';" -U postgres
script:
- npm run build
- npm test
env:
  matrix:
  - DATBASE_URL = "WlKIkdKkhUeQIzPyxoxRDfMkFC5vQzTNht2jQFUJVNMX0btE43fFJPK0lOOV5Ra4ljo1Mjmn9Dg6JuV3ImMGNjDLREQij08oZBDvhXOAlyG/TwgrAXZUi0tuziVgSOQbZ+c8QB5MVe/M4o+xuDQqUhVJAuTP7EM4ZJCgPA+vjPa3zze6DRdImfTRAcR+3Wa8nGMJamKxmFd67dL59iZ0sK5mfQcWgFMBWnWzzZqeafJx12HxJ/NO9JLNGxiQkIN1mBq8oLtJlAFprRQBzWoFqOgTJfcBKu4vfoZXpg7cTxpAbEK90ZFO7XeC+keZpXX989EtgLAj+OkfUeQsVLMQIFJg1q3mkxrmb9ebvOpEPG4NXRQ+JDbNCek9BarTxGpkK94a1IFM9UIq8D75J3UGLnCXCmBmwhm8Ug6qehrUxcM7em2NNOrYheq+yWPlQFHnnxV4kTmfAztrodBVX/E7OsLEwcSzsVnQWT22iYRo/XUknthe0KEP8UO1lehvG6c169+p6DFs9fMGLMLmfO3Xbk93XTS2YDOm+UxyII5L0TcQWJfS47flKynX4kAKTb6I83XpDDbwy3JKQd+udHsYR9JigEfkJVLHG26xD6Hs03B7fmRvTDU968lyr4tuXcWqyyjxViZMON/reK7y2x3J8DYEkpMuZG1ISayk/6YOHgw="