language: node_js
node_js:
- stable
services:
- postgresql
before_script:
- psql -c 'create database monday;' -U postgres
- psql -c "CREATE USER admin WITH PASSWORD '12345';" -U postgres
script:
- npm run setup:db
- npm test
env:
  global:
  - secure: SOoXJX1O81r23NIU5eE6Zqly9/y+7gpM+Ct6YoelmqZ6B/RSiPJg4uOaOh7PKxIv0jJRVfWdVyJkn37+2JBkz/n3SqA7HjKNfyUG16WaMdLlODu3lJ7jbQQm2Hu4P51m7/JiBz2PPyH7ZF3ni73XR3mfoX1A6wP1FRUPlMWAuUNJB5mhZUoN269Hvi33VR16pF4C8TuzltqEczhwoNAtsRnxhl+XTlrD5vaNnIEuac+BUbYmoJLKODvBt91mcVM01lcqGVC8mo5DQ/U+01dUaK543eW17Q1WyxMxUwkGuUIqtoLpCCJnil03vXcqxiA/FlYbSxpuUUAd9GJ1zvP7AVIhQA5/4SNMQydCksaqXw+jAqV/PKX1owrrcGT9RARFCvkeae8oTAbvHUlVG4SR8EyO4XmKvnW+/KdkaUj1EOCEWvtPydCCFfIBROGc2NkuI8oO8tZ2oePzJTX9PTMEIu3jBhDmG5473fuhRV7DhT8O1FmjHkJ1HVSnHUALR8kdJp773GVM4s+hfNT0V/PA03hSNbA6Xx6ZPgwiBAFm1Tgj/I0Tqhsg2869WH1XYG7Rm/jKbvEnZDV8KVvH0G3nLrqv6fZXG2Uu00bQDgBkxHqbiA712dMsiAleKlhlefQRauPbGyiaFA0y5iS98qZE7kAsEcXd93Vn9sjGjDmmp8c=
